apiVersion: v1
kind: Service
metadata:
  name: {{ include "andy-wildlife-ui.fullname" . }}
  labels:
    {{- include "andy-wildlife-ui.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  selector:
    app.kubernetes.io/name: {{ include "andy-wildlife-ui.name" . }}
    app.kubernetes.io/component: ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: 8080
